name: submit-azure-machine-learning-job

trigger:
- none

variables:
  service-connection: 'MLops_testing' # replace with your service connection name
  resource-group: 'Gopi_IT' # replace with your resource group name
  workspace: 'testing_azureml' # replace with your workspace name

jobs:
- job: SubmitAzureMLJob
  displayName: Submit AzureML Job
  timeoutInMinutes: 300
  pool:
    name: test_self_hosted
  steps:
  - task: UsePythonVersion@0
    displayName: Use Python >=3.8
    inputs:
      versionSpec: '>=3.8'

  - powershell: |
      $ErrorActionPreference = "Stop"

      az version
      az extension add --name ml
    displayName: 'Add AzureML Extension'

  - task: AzureCLI@2
    name: submit_azureml_job_task
    displayName: Submit AzureML Job Task
    inputs:
      azureSubscription: $(service-connection)
      workingDirectory: 'cli/jobs/pipelines-with-components/nyc_taxi_data_regression'
      scriptLocation: inlineScript
      scriptType: ps
      inlineScript: |
      
        # Submit component job and get the run name
        $jobName = az ml job create --file single-job-pipeline.yml -g $(resource-group) -w $(workspace) --query name --output tsv

        # Set output variable for next task
        Write-Output "##vso[task.setvariable variable=JOB_NAME;isOutput=true;]$jobName"
  
- job: WaitForAzureMLJobCompletion
  displayName: Wait for AzureML Job Completion
  pool: server
  timeoutInMinutes: 0
  dependsOn: SubmitAzureMLJob
  variables: 
    # We are saving the name of azureMl job submitted in previous step to a variable and it will be used as an inut to the AzureML Job Wait task
    azureml_job_name_from_submit_job: $[ dependencies.SubmitAzureMLJob.outputs['submit_azureml_job_task.JOB_NAME'] ] 
  steps:
  - task: AzureMLJobWaitTask@1
    inputs:
      serviceConnection: $(service-connection)
      resourceGroupName: $(resource-group)
      azureMLWorkspaceName: $(workspace)
      azureMLJobName: $(azureml_job_name_from_submit_job)